void _puts_recursion(char *);
int _putchar(char );
void _print_rev_recursion(char *);
int _strlen_recursion(char *);
int factorial(int );
int _pow_recursion(int, int);
int _sqrt_recursion(int);
int _finder_sqrt(int, int);
int is_prime_number(int);
int actual_prime(int, int);
