int _putchar(char c);
void reset_to_98(int *);
void swap_int(int *, int *);
int _strlen(char *);
void _puts(char *a);
void print_rev(char *);
void rev_string(char *s);
void puts2(char *);
void puts_half(char *);
void print_array(int *, int);
char *_strcpy(char *, char *);
